close #9
atsushimemet/vook_web_front_v1 pull request #12
Opened 2023-03-25 05:15 UTC by garammasala29

- Desktop
![image](https://user-images.githubusercontent.com/69446373/227697748-3cf28f49-9ebd-47f9-9222-e76d8fcaa58e.png)

- Mobile
 <img src="https://user-images.githubusercontent.com/69446373/227697723-40d901ad-3915-4f55-8f93-10c5cc4b2789.png" width="50%" />

アニメーションについては別issueに切り出す

2023-03-25 05:20 UTC, garammasala29 commented
@atsushimemet 
現時点でのデザインです。ご確認お願いします。

2023-03-26 10:51 UTC, atsushimemet requested changes
@garammasala29 
本件、ありがとう!
イメージ通りのデザインで小澤は問題なしです!
たまりさんからのデザイン関連の指摘もあるので、デザインに関しての修正は少々お待ちください。
ref: https://vook-co.slack.com/archives/C04P4S8BZKP/p1679722604664929

他、瑣末な点ですが指摘させてください!
- [ ] 画像ファイルはgitignoreに含めてバージョン管理しない
- [ ] 画像ファイルは、一旦[こちら](https://drive.google.com/drive/folders/12it0BXJaLbMh1xPiOZuR1lRzrc2_Yr2w?usp=share_link)に格納 ※ 他にやり方案あれば是非

以上、よろしくお願いします。

2023-03-26 13:04 UTC, garammasala29 commented
@atsushimemet 
> 画像ファイルはgitignoreに含めてバージョン管理しない

この方針に沿って修正しました。
[こちら](https://vook-co.slack.com/archives/C04P4S8BZKP/p1679830382875649?thread_ts=1679722604.664929&cid=C04P4S8BZKP)のフォント修正に関しては次のプルリクで反映させます。

2023-03-29 02:07 UTC, atsushimemet commented
@garammasala29 
下記レビュー対応お願いします！
https://vook-co.slack.com/archives/C04P4S8BZKP/p1679830382875649?thread_ts=1679722604.664929&channel=C04P4S8BZKP&message_ts=1679830382.875649

1. 見出しの数字と見出しのフォントサイズ変更
2. インパクトのあるフォントに変更

それぞれ、たまりさんにデザインを見せて認識合えばソース修正で、お願いします！

2023-03-30 15:27 UTC, garammasala29 commented
今回は対応せず、vook_web_v3の開発に移ります。
ref: https://vook-co.slack.com/archives/C04P4S8BZKP/p1680189838052189?thread_ts=1680185959.229299&cid=C04P4S8BZKP

2023-03-30 15:28 UTC, merged